# Deployment Rolling Update
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappdeployment
  namespace: kenny
spec:
  replicas: 3
  selector:
    matchLabels:
      app: javawebapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 30
  template:
    metadata:
      name: javawebapppod
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebappcontainer
        image: kenthadocker/kenny-image:2 
        ports:
        - containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappservice
  namespace: kenny
spec:
  type: NodePort  #ClusterIP
  selector:
     app: javawebapp
  ports:
  - port: 80
    targetPort: 8080
  
